
# Constants
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
WINDOW_TITLE = "OH HERMES SEND THE MESSAGE"

# Constants used to scale our sprites from their original size
TILE_SCALING = 1.5
COIN_SCALING = 0.5

# Movement speed of player, in pixels per frame
PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 0.3
PLAYER_JUMP_SPEED = 8
DASH_SPEED = 15
DASH_DURATION = 0.15
DASH_COOLDOWN = 0.6
DASH_INPUT_LOCK_TIME = 0.5
DOUBLE_JUMP_LOCK_TIME = 0.4
WALL_SLIDE_SPEED = -3
WALL_JUMP_FORCE_X = 6
WALL_JUMP_FORCE_Y = 6
WALL_JUMP_REPEAT_FORCE_X = 6
WALL_JUMP_REPEAT_FORCE_Y = 6
WALL_JUMP_LOCK_TIME = 0.2

# Constants used to track the direction a character is facing
RIGHT_FACING = 0
LEFT_FACING = 1
